apiVersion: v1
kind: Service
metadata:
  name: {{ include "wiki-chart.fullname" . }}-postgres
  labels:
    {{- include "wiki-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "wiki-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
